version: 2

updates:
- directory: '/admin'
  package-ecosystem: 'npm'
  schedule:
    interval: 'weekly'
    time: '08:00'
    day: 'saturday'
    timezone: 'Europe/Berlin'
  groups:
    npm-dependencies-frontend:
      patterns:
        - '*'

- directory: '/lambdas'
  package-ecosystem: 'npm'
  schedule:
    interval: 'weekly'
    time: '08:00'
    day: 'saturday'
    timezone: 'Europe/Berlin'
  groups:
    npm-dependencies-lambdas:
      patterns:
        - '*'

- directory: '/backend'
  package-ecosystem: 'composer'
  schedule:
    interval: 'weekly'
    time: '08:00'
    day: 'saturday'
    timezone: 'Europe/Berlin'
  groups:
    composer-dependencies:
      patterns:
        - '*'
    
- directory: '/android'
  package-ecosystem: 'gradle'
  schedule:
    interval: 'weekly'
    time: '08:00'
    day: 'saturday'
    timezone: 'Europe/Berlin'
  groups:
    gradle-dependencies:
      patterns:
        - '*'

- directory: '/'
  package-ecosystem: 'github-actions'
  schedule:
    interval: 'monthly'
  groups:
    github-dependencies:
      patterns:
        - '*'
