# Generated by Django 5.2.1 on 2025-05-09 09:03

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('roles', models.JSONField(db_comment='(DC2Type:json)')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('pk', models.CompositePrimaryKey('station_id', 'date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('station_id', models.UUIDField(db_comment='(DC2Type:uuid)')),
                ('version', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('version_code', models.IntegerField(blank=True, null=True)),
                ('online', models.BooleanField()),
            ],
            options={
                'db_table': 'app_info',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=265)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('sort_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'field',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('sort_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='CrewInfo',
            fields=[
                ('pk', models.CompositePrimaryKey('station_id', 'date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=10)),
                ('station_id', models.UUIDField(db_comment='(DC2Type:uuid)')),
                ('crew', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crew_info',
                'unique_together': {('station_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SpecialEvent',
            fields=[
                ('id', models.UUIDField(db_comment='(DC2Type:uuid)', primary_key=True, serialize=False)),
                ('title', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255)),
                ('note', models.TextField(db_collation='utf8mb4_unicode_ci')),
                ('date', models.DateTimeField()),
                ('notifier', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=64)),
                ('type', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=6)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beachist.station')),
            ],
            options={
                'db_table': 'special_event',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(db_comment='(DC2Type:uuid)', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('firstAid', 'Erste Hilfe'), ('search', 'Suchmeldung')], max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beachist.station')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
                ('state_kind', models.CharField(blank=True, choices=[('broken', 'Defekt'), ('tooLittle', 'Zu wenig'), ('other', 'Andere')], max_length=10, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateTimeField()),
                ('crew', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beachist.field')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beachist.station')),
            ],
            options={
                'db_table': 'entry',
            },
        ),
        migrations.CreateModel(
            name='StationField',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('required', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beachist.field')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beachist.station')),
            ],
            options={
                'db_table': 'station_field',
            },
        ),
        migrations.CreateModel(
            name='StationProvisioningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beachist.station')),
            ],
            options={
                'db_table': 'station_provisioning_request',
            },
        ),
    ]
