# Generated by Django 5.2.1 on 2025-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachist', '0002_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('payload', models.CharField(max_length=255)),
                ('payload_type', models.IntegerField(choices=[(0, 'Plain'), (1, 'Binary')])),
                ('qos', models.IntegerField()),
                ('retain', models.BooleanField()),
                ('ts', models.DateTimeField()),
            ],
        ),
    ]
