name: admin_test

on:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: install node
      uses: actions/setup-node@v3.0.0
      with:
        node-version: '14.x'

    - name: npm ci
      run: npm ci
      working-directory: admin

    - name: npm build
      run: npm run build
      working-directory: admin
      
    - name: npm test
      run: npm test
      working-directory: admin
