name: android_test

on:
  pull_request:

jobs:
  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.android }}
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          android:
            - 'android/**'

  test:
    needs: determine_changes
    if: needs.determine_changes.outputs.changes == 'true'
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup configs
        working-directory: android
        run: |
          echo -e "backendUrl=\"https://example.com\"\ndatabaseName=\"wachmanager-test\"\nprovisioningUrl=\"https://verysecret.lambda-url.eu-central-1.on.aws/\"" > ./project_resources/config.properties

      - name: run tests
        working-directory: android
        # todo: re-add linting
        run: ./gradlew testDebug --continue --stacktrace

  emulator_test:
    needs: determine_changes
    if: needs.determine_changes.outputs.changes == 'true'
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup configs
        working-directory: android
        run: |
          echo -e "backendUrl=\"https://example.com\"\ndatabaseName=\"wachmanager-test\"\nprovisioningUrl=\"https://verysecret.lambda-url.eu-central-1.on.aws/\"" > ./project_resources/config.properties

      - name: run tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: x86_64
          force-avd-creation: false
          avd-name: macOS-avd-x86_64-31
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          api-level: 30
          script: ./gradlew connectedDebugAndroidTest --stacktrace
          working-directory: android
