name: android_test

on:
  pull_request:

jobs:
  determine_changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.android }}
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          android:
            - 'android/**'

  test:
    needs: determine_changes
    if: needs.determine_changes.outputs.changes == 'true'
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup configs
        working-directory: android
        run: |
          echo -e "backendUrl=\"https://example.com\"\ndatabaseName=\"wachmanager-test\"" > ./project_resources/config.properties

      - name: run tests
        working-directory: android
        run: ./gradlew lint testDebug --continue --stacktrace

  emulator_test:
    needs: determine_changes
    if: needs.determine_changes.outputs.changes == 'true'
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup configs
        working-directory: android
        run: |
          echo -e "backendUrl=\"https://example.com\"\ndatabaseName=\"wachmanager-test\"" > ./project_resources/config.properties

      - name: run tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 24
          script: ./gradlew connectedDebugAndroidTest --stacktrace
          working-directory: android
