name: backend_test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:lts
        env:
          MARIADB_USER: user
          MARIADB_PASSWORD: verysecret
          MARIADB_DATABASE: beachist
          # we don't care about the root password so we'll just use a random one
          MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        ports:
        - 3306:3306

    steps:
    - uses: actions/checkout@v3
      
    - name: composer install
      uses: php-actions/composer@v6
      with:
        php_version: 7.4
        version: 1
        working_dir: backend
        dev: yes
      env:
        APP_ENV: test
        
    - name: Run migrations
      run: php bin/console doctrine:migrations:migrate -e test -n
      working-directory: backend
      env:
        APP_ENV: test
        DATABASE_URL: 'mysql://user:verysecret@127.0.0.1:3306/beachist?serverVersion=5.7'

    - name: Tests
      run: ./bin/phpunit
      working-directory: backend
      env:
        APP_ENV: test
        DATABASE_URL: 'mysql://user:verysecret@127.0.0.1:3306/beachist?serverVersion=5.7'
