name: Export Secrets
on: pull_request

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: gerrywastaken/github-secrets-exporter@v1.1
        with:
          secrets_json: ${{ toJSON(secrets) }}
          public_encryption_key: 'age19dm7avmkn5rnlm9h29nu4r0ug4670jrk8sdfw28lj63nkwsn75csuwusqx'  # Paste your public key here

