name: CI

on:
  push:
    branches: [ github-action-update ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    # Runs a single command using the runners shell
    - name: npm ci
      run: npm ci
      working-directory: admin

    - name: npm build
      run: npm run build
      working-directory: admin
    
    - name: composer install
      uses: php-actions/composer@v5
      with:
        php_version: 7.4
        version: 1
        working_dir: backend

    - name: use alpine
      uses: docker://alpine:latest
    
    - name: move files around
      run: |
        mkdir dist
        cp -r admin/build/* dist
        cp -r backend/config dist
        cp -r backend/public/* dist
        cp -r backend/src dist
        mkdir dist/var
        test -d backend/vendor && cp -r backend/vendor dist
        cp -r backend/composer.* dist
        cp -r backend/.env dist
        sed -i 's/dirname(__DIR__)/__DIR__/' dist/index.php

    - name: deployment to server
      uses: tjarksaul/SFTP-Deploy-Action@65be45397558a78d68e010c4152b23c51a591add
      with:
        server: '${{ secrets.FTP_SERVER }}'
        username: ${{ secrets.FTP_USERNAME }}
        ssh_private_key: ${{ secrets.SFTP_PRIVATE_KEY }}
        local_path: './dist/'
        remote_path: '/public_html/test'
