name: npm_check_update
on:
  workflow_dispatch: {}
  schedule:
    # At 04:00 UTC on Saturday 
    - cron: 0 4 * * 6

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.UPDATE_PR_APP_ID }}
        private_key: ${{ secrets.UPDATE_PR_APP_PRIVATE_KEY }}
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - name: Update Dependencies
      working-directory: admin
      run: |
        npm ci
        npx ncu
        npm install
        npm update
    - name: Update Dependencies
      working-directory: lambdas
      run: |
        npm ci
        npx ncu
        npm install
        npm update
    - name: Create Pull Request
      with:
        token: ${{ steps.generate-token.outputs.token }}
        committer: GitHub Actions <actions@github.com>
        commit-message: 'Update npm dependencies 🚀'
        title: 'Update npm dependencies 🚀'
        body: 'See diff'
        author: GitHub Actions <actions@github.com>
        branch: dependency-update
        branch-suffix: timestamp
      uses: peter-evans/create-pull-request@v4
